#!/usr/bin/env ruby
#^syntax detection


require 'certified'

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git'
cookbook 'sqlite'
cookbook 'vim'
cookbook 'mysql'
cookbook 'mysql2_chef_gem'
cookbook 'postgresql'
cookbook 'database'
cookbook 'nodejs'
cookbook 'build-essential'
cookbook 'ruby_build'
cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-rbenv.git', :ref => 'v0.8.0'
